services:
  - type: web
    name: convert-my-file
    runtime: docker
    plan: free
    startCommand: "gunicorn --bind 0.0.0.0:10000 --timeout 120 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
